Shut up, logs!

diff --git a/rootfs/etc/template/dumpvdl2/run b/rootfs/etc/template/dumpvdl2/run
--- a/rootfs/etc/template/dumpvdl2/run
+++ b/rootfs/etc/template/dumpvdl2/run
@@ -35,6 +35,10 @@ VDLM_CMD+=("--gain" "$GAIN" "--station-id" "$STATION_ID_VDLM")
 VDLM_CMD+=("--msg-filter" "all,-avlc_s,-acars_nodata,-x25_control,-idrp_keepalive,-esis")
 VDLM_CMD+=("--station-id=$STATION_ID_VDLM" "--output" "decoded:json:udp:address=127.0.0.1,port=5555")
 
+if [ -z "${QUIET_MESSAGES}" ]; then
+  VDLM_CMD+=("--output" "decoded:text:file:path=-")
+fi
+
 if [ -n "${PLANEPLOTTER}" ] && [ -n "$ENABLE_VDLM" ]; then
 	VDLM_CMD+=("--output" "decoded:pp_acars:udp:address=127.0.0.1,port=4444")
 
@@ -57,10 +61,31 @@ VDLM_CMD+=($FREQS_VDLM)
 
 set -eo pipefail
 
-echo "[dumpvdl2-$SERIAL] Starting: '$VDLM_BIN" "${VDLM_CMD[*]}'"
+if [[ -n "${QUIET_LOGS}" ]]; then
+  # shellcheck disable=SC2016
+  "$VDLM_BIN" "${VDLM_CMD[@]}" 2>&1 | \
+  stdbuf -oL sed --unbuffered '/^$/d' | \
+  stdbuf -oL awk '! /^dumpvdl2/' | \
+  stdbuf -oL awk '! /^Sampling rate set/' | \
+  stdbuf -oL awk '! /^Found \d+ device(s):/' | \
+  stdbuf -oL awk '! /^  [0-9]+/' | \
+  stdbuf -oL awk '! /^Using device [0-9]+/' | \
+  stdbuf -oL awk '! /^Found /' | \
+  stdbuf -oL awk '! /^Exact sample rate /' | \
+  stdbuf -oL awk '! /^Setting sample rate/' | \
+  stdbuf -oL awk '! /PLL not locked!$/' | \
+  stdbuf -oL awk '! /^Center frequency set/' | \
+  stdbuf -oL awk '! /^Device [#]?[0-9]+/' | \
+  stdbuf -oL awk '{print "[dumpvdl2] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
+else
+  echo "[dumpvdl2-$SERIAL] Starting: '$VDLM_BIN" "${VDLM_CMD[*]}'"
+  # shellcheck disable=SC2016
+  "$VDLM_BIN" "${VDLM_CMD[@]}" 2>&1 | \
+  stdbuf -oL sed --unbuffered '/^$/d' | \
+  stdbuf -oL awk '{print "[dumpvdl2] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
+fi
 
-# shellcheck disable=SC2016
-"$VDLM_BIN" "${VDLM_CMD[@]}" \
-2>&1 | stdbuf -oL sed --unbuffered '/^$/d' | stdbuf -oL awk '{print "[dumpvdl2] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
-
+# if we've ended up here there is a problem!
+echo "[dumpvdl2-$SERIAL] Exiting with error"
 sleep 5
+exit 1
