Move serial to device mapping to assign_frequencies.py

diff --git a/rootfs/etc/template/acarsdec/run b/rootfs/etc/template/acarsdec/run
--- a/rootfs/etc/template/acarsdec/run
+++ b/rootfs/etc/template/acarsdec/run
@@ -5,7 +5,8 @@
 #  - acarsdec does not depend on any services and should start immediately
 
 ACARS_BIN="/usr/local/bin/acarsdec"
-SERIAL=""
+#SERIAL=""
+DEVICE_ID=""
 # shellcheck disable=SC2001
 FREQS_ACARS=""
 PPM=""
@@ -37,24 +38,33 @@ fi
 # Send output JSON to acars_server
 ACARS_CMD+=("-j" '127.0.0.1:5550')
 
-if [ -n "${SERIAL}" ]; then
+# if [ -n "${SERIAL}" ]; then
 
-	set -e
+# 	set -e
 
-	if [ -n "${BYPASS_SDR_CHECK}" ]; then
-		DEVICE_ID=$SERIAL
-	elif [ -n "${QUIET_LOGS}" ]; then
-		DEVICE_ID="$(rtl_serial_to_deviceid.sh -s "$SERIAL")"
-	else
-		DEVICE_ID="$(rtl_serial_to_deviceid.sh -v -s "$SERIAL")"
-	fi
+# 	if [ -n "${BYPASS_SDR_CHECK}" ]; then
+# 		DEVICE_ID=$SERIAL
+# 	elif [ -n "${QUIET_LOGS}" ]; then
+# 		DEVICE_ID="$(rtl_serial_to_deviceid.sh -s "$SERIAL")"
+# 	else
+# 		DEVICE_ID="$(rtl_serial_to_deviceid.sh -v -s "$SERIAL")"
+# 	fi
 
-	set +e
+# 	set +e
+
+# 	ACARS_CMD+=("-r" "$DEVICE_ID") 
+
+# else
+# 	echo "[acarsdec] No serial number set. Using device index 0. If also running VDLM decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
+# 	ACARS_CMD+=("-r" "0")
+# fi
+
+if [ -n "${DEVICE_ID}" ]; then
 
 	ACARS_CMD+=("-r" "$DEVICE_ID") 
 
 else
-	echo "[acarsdec] No serial number set. Using device index 0. If also running VDLM decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
+	echo "[acarsdec] No serial number / device index set. Using device index 0. If also running VDLM decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
 	ACARS_CMD+=("-r" "0")
 fi
 
diff --git a/rootfs/etc/template/vdlm2dec/run b/rootfs/etc/template/vdlm2dec/run
--- a/rootfs/etc/template/vdlm2dec/run
+++ b/rootfs/etc/template/vdlm2dec/run
@@ -5,7 +5,8 @@
 #  - vdlm2dec does not depend on any services and should start immediately
 
 VDLM_BIN="/usr/local/bin/vdlm2dec"
-SERIAL=""
+#SERIAL=""
+DEVICE_ID=""
 # shellcheck disable=SC2001
 FREQS_VDLM=""
 PPM=""
@@ -30,24 +31,33 @@ fi
 # Send output JSON to vdlm2_server.
 VDLM_CMD+=("-j" "127.0.0.1:5555")
 
-if [ -n "${SERIAL}" ]; then
+# if [ -n "${SERIAL}" ]; then
 
-	set -e
+# 	set -e
 
-	if [ -n "${BYPASS_SDR_CHECK}" ]; then
-		DEVICE_ID=$SERIAL
-	elif [ -n "${QUIET_LOGS}" ]; then
-		DEVICE_ID="$(rtl_serial_to_deviceid.sh -s "$SERIAL")"
-	else
-		DEVICE_ID="$(rtl_serial_to_deviceid.sh -v -s "$SERIAL")"
-	fi
+# 	if [ -n "${BYPASS_SDR_CHECK}" ]; then
+# 		DEVICE_ID=$SERIAL
+# 	elif [ -n "${QUIET_LOGS}" ]; then
+# 		DEVICE_ID="$(rtl_serial_to_deviceid.sh -s "$SERIAL")"
+# 	else
+# 		DEVICE_ID="$(rtl_serial_to_deviceid.sh -v -s "$SERIAL")"
+# 	fi
 
-	set +e
+# 	set +e
+
+# 	VDLM_CMD+=("-r" "$DEVICE_ID")
+
+# else
+# 	echo "[vdlm2dec] No serial number set. Using device index 0. If also running ACARS decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
+# 	VDLM_CMD+=("-r" "0")
+# fi
+
+if [ -n "${DEVICE_ID}" ]; then
 
 	VDLM_CMD+=("-r" "$DEVICE_ID")
 
 else
-	echo "[vdlm2dec] No serial number set. Using device index 0. If also running ACARS decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
+	echo "[vdlm2dec] No serial number / device index set. Using device index 0. If also running ACARS decoding one of these processes will fail. To fix, set SERIAL_ACARS and SERIAL_VDLM"
 	VDLM_CMD+=("-r" "0")
 fi
 
