enable external mode for pushing data into acarshub via UDP

diff --git a/rootfs/etc/cont-init.d/01-acarshub b/rootfs/etc/cont-init.d/01-acarshub
--- a/rootfs/etc/cont-init.d/01-acarshub
+++ b/rootfs/etc/cont-init.d/01-acarshub
@@ -11,14 +11,28 @@ FREQ_CMD=()
 pushd ../../scripts > /dev/null 2>&1 || exit 1
 python3 acars-sanity-checker.py || exit 1
 
-if [ -n "${ENABLE_ACARS}" ]; then
+
+# Just in case the container was docker restart we should clean up some dirs if present
+# thanks k1xt
+
+rm -rf /etc/services.d/acarsdec-* /etc/services.d/vdlm2dec-* >/dev/null 2>&1
+
+GENERATE=false
+
+if [[ "${ENABLE_ACARS}" == "external" ]]; then
+    echo "ACARS Decoder set to external, push data to UDP port 5550" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
+elif [ -n "${ENABLE_ACARS}" ] && [[ "${ENABLE_ACARS}" != "external" ]]; then
+    GENERATE=true
 	if [ -n "${FREQS_ACARS}" ]; then
 		IFS=';' read -r -a ACARS_ARRAY <<< "$FREQS_ACARS"
 		FREQ_CMD+=("-a" "${ACARS_ARRAY[@]}")
 	fi
 fi
 
-if [ -n "${ENABLE_VDLM}" ]; then
+if [[ "${ENABLE_VDLM}" == "external" ]]; then
+    echo "VDLM Decoder set to external, push data to UDP port 5555" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
+elif [ -n "${ENABLE_VDLM}" ]; then
+    GENERATE=true
 	if [ -n "${FREQS_VDLM}" ]; then
 		IFS=';' read -r -a VDLM_ARRAY <<< "$FREQS_VDLM"
 		FREQ_CMD+=("-v" "${VDLM_ARRAY[@]}")
@@ -26,18 +40,16 @@ if [ -n "${ENABLE_VDLM}" ]; then
 fi
 
 if [ -n "${SERIAL}" ]; then
+    GENERATE=true
 	IFS=';' read -r -a SERIAL_ARRAY <<< "$SERIAL"
 	FREQ_CMD+=("-s" "${SERIAL_ARRAY[@]}")
 fi
 
-echo "Generating decoder startup files" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
-
-# Just in case the container was docker restart we should clean up some dirs if present
-# thanks k1xt
-
-rm -rf /etc/services.d/acarsdec-* /etc/services.d/vdlm2dec-* >/dev/null 2>&1
+if [[ "$GENERATE" == "true" ]]; then
+    echo "Generating decoder startup files" | awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
 # shellcheck disable=SC2016
-python3 assign_frequencies.py "${FREQ_CMD[@]}" | stdbuf -oL awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' || exit 1
+    python3 assign_frequencies.py "${FREQ_CMD[@]}" | stdbuf -oL awk '{print "[01-acarshub] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' || exit 1
+fi
 
 # Ensure /database dir is present
 
