Site ID for VDLM and ACARS

diff --git a/rootfs/etc/cont-init.d/01-set-values b/rootfs/etc/cont-init.d/01-set-values
--- a/rootfs/etc/cont-init.d/01-set-values
+++ b/rootfs/etc/cont-init.d/01-set-values
@@ -1,12 +1,12 @@
 #!/usr/bin/with-contenv sh
 # shellcheck shell=sh
 
-if [ -n "${STATON_ID}" ]; then
-	echo "Error: No STATION_ID set. Exiting"
-	exit 1
-fi
-
 if [ -n "${ENABLE_ACARS}" ]; then
+	if [ -n "${STATON_ID_ACARS}" ]; then
+		echo "Error: No STATION_ID set. Exiting"
+		exit 1
+	fi
+
 	if [ -z "${FREQS_ACARS}" ]; then
 		echo "Error: ACARS enabled with no FREQS_ACARS. Exiting"
 		exit 1
@@ -14,6 +14,10 @@ if [ -n "${ENABLE_ACARS}" ]; then
 fi
 
 if [ -n "${ENABLE_VDLM}" ]; then
+	if [ -n "${STATON_ID_VDLM}" ]; then
+		echo "Error: No STATION_ID set. Exiting"
+		exit 1
+	fi
 	if [ -z "${FREQS_VDLM}" ]; then
 		echo "Error: VDLM enabled with no FREQS_VDLM. Exiting"
 		exit 1
